# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20160709_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='icon',
            field=models.ImageField(default='member/static/images/members_icon/default/icon.png', upload_to='members_icon/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='intro_body',
            field=models.TextField(blank=True, default='Default'),
        ),
        migrations.AlterField(
            model_name='member',
            name='title',
            field=models.CharField(blank=True, default='Default', max_length=140),
        ),
    ]
