# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import member.models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20160709_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='icon',
            field=models.ImageField(upload_to=member.models.get_upload_path),
        ),
    ]
