# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_news_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'news'},
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
